language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "nightly"
env:
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10rc1
before_install: 
  - set -ev
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/debian wheezy/snapshots/4.0.0 main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
  - echo "deb http://download.mono-project.com/repo/debian wheezy-libtiff-compat main" | sudo tee -a /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get update
  - sudo apt-get install mono-complete -y
  - sudo apt-get install p7zip -y
  - sudo apt-get install liblog4cxx10 -y  
  - cd scriptnet
install: 
  - pip install Django==$DJANGO_VERSION
  - pip install django-bootstrap3 django_tables2
script: python manage.py test competitions
