sudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "nightly"
env:
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10rc1
before_install: 
  - set -ev
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - sudo echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get update  
  - sudo apt-get install mono-complete -y
  - sudo apt-get install p7zip -y
  - sudo apt-get install liblog4cxx10 -y
  - sudo apt-get install libopencv-dev -y
  - sudo apt-get install uni2ascii -y
  - cd scriptnet
install: 
  - pip install Django==$DJANGO_VERSION
  - pip install django-bootstrap3 django_tables2
script: python manage.py test competitions